# configure updates globally, default is all
update: all # allowed [all, insecure, False]

# configure dependency pinning globally, default is True
pin: True # allowed [True, False]

# set the default branch, default is the default branch on GitHub
branch: dev

# update schedule, default is not set
# the bot will visit the repo once and bundle all updates in a single PR for the given
# day/week/month
schedule: "every week" # allowed ["every day", "every week", "every two weeks", "every month"]

# configure requirement files search, default is True
# the bot will search for files ending with .txt/.pip with a requirements in their file paths
search: True # allowed [True, False]

# assign users to pull requests, default is not set
# requires private repo permissions, even on public repos
assignees:
 - dbsmith88
 - dmlyons2
 - kurtw555
 - popenc
 - puruckertom
